name: Build and Test
on: [push]
jobs:
  build:
    runs-on: windows-latest
    env:
      GitHubActionsLogger_Debug: True
      GitHubActionsMSBuildLogger_MsBuildPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe
    steps:
    - name: Checkout commit
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - uses: StanleyGoldman/setup-GitHubActionsMSBuildLogger@master
    - name: Build
      run: |
        dotnet build -c Release .\GitHubActionsMSBuildLogger.sln -v normal -fl -flp:logfile=build.log -flp:verbosity=detailed /logger:GitHubActionsLogger,..\GitHubActionsMSBuildLogger.dll
    - name: Test
      if: success() && startsWith(github.ref, 'refs/heads')
      run: |
        $env:GitHubActionsMSBuildLogger_LoggerPath = "$pwd\src\GitHubActionsMSBuildLogger\bin\Release\netstandard1.3\GitHubActionsMSBuildLogger.dll"
        $env:GitHubActionsMSBuildLogger_TestResourcePath = "$pwd\test-resources"
        .\test.ps1
    - name: Upload Build Log
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Build
        path: build.log
    - name: Upload Reports
      if: always() && startsWith(github.ref, 'refs/heads')
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Reports
        path: reports
    - name: Upload Binaries
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Binaries
        path: src\GitHubActionsMSBuildLogger\bin\Release\netstandard1.3
    - name: Tag commit
      uses: tvdias/github-tagger@v0.0.1
      if: success() && github.ref == 'refs/heads/master'
      with:
        repo-token: "${{ secrets.GH_TOKEN }}"
        tag: "${{ format('v{0}', env.GitVersion_MajorMinorPatch) }}"
    - name: Create a Release        
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      uses: actions/create-release@v1
      if: success() && startsWith(github.ref, 'refs/tags')
      with:
        tag_name: "${{ format('v{0}', env.GitVersion_MajorMinorPatch) }}"
        release_name: "${{ format('v{0}', env.GitVersion_MajorMinorPatch) }}"
        body: "${{ format('v{0}', env.GitVersion_MajorMinorPatch) }}"
    - name: Checkout setup project
      uses: actions/checkout@v2-beta
      if: success() && startsWith(github.ref, 'refs/tags')
      with:
        repository: 'StanleyGoldman/setup-GitHubActionsMSBuildLogger'
        ref: 'master'
        token: ${{ secrets.GH_TOKEN }}
        path: 'setup-GitHubActionsMSBuildLogger'
        lfs: 'true'
    - name: Update setup project
      if: success() && startsWith(github.ref, 'refs/tags')
      run: |
        cp -Force "$pwd\src\GitHubActionsMSBuildLogger\bin\Release\netstandard1.3\GitHubActionsMSBuildLogger.dll" setup-GitHubActionsMSBuildLogger\
        cd setup-GitHubActionsMSBuildLogger\
        git add -A
        git commit -m "Update to v$env.GitVersion_MajorMinorPatch"
        git tag "v$env.GitVersion_MajorMinorPatch"
        git push --tags origin master
