name: Build and Test
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout commit
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 3.0.100
    - name: Build and Test
      run: |
        git checkout master
        $branchName = $env:GITHUB_REF.Trimstart("refs/heads/")
        git checkout -b $branchName
        git reset --hard $env:GITHUB_SHA
        .\build.ps1
        $env:GitHubActionsMSBuildLogger_LoggerPath = "$pwd\src\GitHubActionsMSBuildLogger\bin\Release\netstandard1.3\GitHubActionsMSBuildLogger.dll"
        $env:GitHubActionsMSBuildLogger_TestResourcePath = "$pwd\test-resources"
        $env:GitHubActionsMSBuildLogger_MsBuildPath = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe"
        .\test.ps1
    - name: Publish to NuGet
      if: github.ref == 'refs/heads/master'
      run: dotnet nuget push src\GitHubActionsMSBuildLogger\bin\Release\*.nupkg -k ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json
    - name: Upload Build Log
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Build
        path: build.log
    - name: Upload Reports
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Reports
        path: reports
    - name: Upload Binaries
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Binaries
        path: src\GitHubActionsMSBuildLogger\bin\Release\
