name: Build master
on:
  push: 
    branches:
      - 'master'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout commit
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build
      run: |
        dotnet build -c Release .\GitHubActionsMSBuildLogger.sln -v normal -fl -flp:logfile=build.log -flp:verbosity=detailed
    - name: Tag commit
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GH_TOKEN }}"
        tag: "${{ format('v{0}', env.GitVersion_SemVer) }}"
    - name: Upload Build Log
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Build
        path: build.log
    - name: Upload Binaries
      if: always()
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Binaries
        path: src\GitHubActionsMSBuildLogger\bin\Release\netstandard1.3
